### ISSUE TITLE
Missing License

### ISSUE THREAD

**Issue by Zvezdin** [doubleblind-xyz/double-blind#5]
Hi, 
I love your RSA & BigInt implementation, it's the only working one I found. I would like to use it in circuits of mine - would you mind adding a license (eg. MIT) so I could be able to use it legally? Thanks!

**Comment by stevenhao** [comment]
sure thing!

**Comment by stevenhao** [comment]
closed in https://github.com/doubleblind-xyz/double-blind/commit/18d1ec474b580fc9169dde09ec148230b332ad40
